const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

const products = [
  {
    name: 'Paracetamol 500mg',
    description: 'Effective pain relief and fever reducer. Suitable for headaches, toothaches, and mild fever.',
    price: 800,
    stock: 150,
    category: 'PAIN_RELIEF',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
    prescriptionRequired: false,
    dosage: '1-2 tablets every 4-6 hours. Max 8 tablets per day.',
    manufacturer: 'PharmaCare Ltd',
    activeIngredient: 'Paracetamol 500mg',
    sideEffects: 'Rare: skin rash, liver damage with overdose',
    featured: true,
  },
  {
    name: 'Ibuprofen 400mg',
    description: 'Non-steroidal anti-inflammatory drug (NSAID) for pain, inflammation and fever.',
    price: 1200,
    stock: 100,
    category: 'PAIN_RELIEF',
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
    prescriptionRequired: false,
    dosage: '1 tablet 3 times daily with food.',
    manufacturer: 'Rwanda Pharma',
    activeIngredient: 'Ibuprofen 400mg',
    sideEffects: 'Stomach upset, heartburn, dizziness',
    featured: false,
  },
  {
    name: 'Amoxicillin 500mg',
    description: 'Broad-spectrum antibiotic for bacterial infections including respiratory and urinary tract infections.',
    price: 3500,
    stock: 80,
    category: 'ANTIBIOTICS',
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
    prescriptionRequired: true,
    dosage: '1 capsule 3 times daily for 7-10 days.',
    manufacturer: 'East Africa Meds',
    activeIngredient: 'Amoxicillin trihydrate 500mg',
    sideEffects: 'Diarrhea, nausea, skin rash, allergic reactions',
    featured: true,
  },
  {
    name: 'Vitamin C 1000mg',
    description: 'High-dose Vitamin C supplement for immune system support and antioxidant protection.',
    price: 2500,
    stock: 200,
    category: 'VITAMINS_SUPPLEMENTS',
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=400',
    prescriptionRequired: false,
    dosage: '1 tablet daily with meals.',
    manufacturer: 'VitaHealth Rwanda',
    activeIngredient: 'Ascorbic Acid 1000mg',
    sideEffects: 'Mild stomach upset at high doses',
    featured: true,
  },
  {
    name: 'Metformin 500mg',
    description: 'First-line medication for type 2 diabetes management. Controls blood sugar levels.',
    price: 4200,
    stock: 60,
    category: 'DIABETES',
    imageUrl: 'https://images.unsplash.com/photo-1576671081803-aa5c6df33da4?w=400',
    prescriptionRequired: true,
    dosage: '1 tablet twice daily with meals.',
    manufacturer: 'DiabaCare Ltd',
    activeIngredient: 'Metformin HCl 500mg',
    sideEffects: 'Nausea, diarrhea, stomach upset',
    featured: false,
  },
  {
    name: 'Omeprazole 20mg',
    description: 'Proton pump inhibitor for acid reflux, heartburn and stomach ulcers.',
    price: 2800,
    stock: 90,
    category: 'DIGESTIVE',
    imageUrl: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400',
    prescriptionRequired: false,
    dosage: '1 capsule daily before breakfast.',
    manufacturer: 'GastroMed Rwanda',
    activeIngredient: 'Omeprazole 20mg',
    sideEffects: 'Headache, diarrhea, stomach pain',
    featured: false,
  },
  {
    name: 'Amlodipine 5mg',
    description: 'Calcium channel blocker for high blood pressure and chest pain (angina).',
    price: 5500,
    stock: 45,
    category: 'CARDIOVASCULAR',
    imageUrl: 'https://images.unsplash.com/photo-1583947213500-8e7b2dc63a87?w=400',
    prescriptionRequired: true,
    dosage: '1 tablet daily at the same time each day.',
    manufacturer: 'CardioPharm',
    activeIngredient: 'Amlodipine besilate 5mg',
    sideEffects: 'Swelling of ankles, flushing, palpitations',
    featured: false,
  },
  {
    name: 'Salbutamol Inhaler 100mcg',
    description: 'Fast-acting bronchodilator for asthma and chronic obstructive pulmonary disease (COPD).',
    price: 6500,
    stock: 35,
    category: 'RESPIRATORY',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1680221452773-afa36111db5b?w=400',
    prescriptionRequired: true,
    dosage: '1-2 puffs as needed. Max 8 puffs per day.',
    manufacturer: 'BreathEasy Corp',
    activeIngredient: 'Salbutamol sulfate 100mcg per puff',
    sideEffects: 'Tremor, headache, increased heart rate',
    featured: true,
  },
  {
    name: 'Multivitamin Complete',
    description: 'Comprehensive daily multivitamin with essential vitamins and minerals for overall health.',
    price: 3200,
    stock: 120,
    category: 'VITAMINS_SUPPLEMENTS',
    imageUrl: 'https://images.unsplash.com/photo-1544991936-9464fa430e37?w=400',
    prescriptionRequired: false,
    dosage: '1 tablet daily with breakfast.',
    manufacturer: 'VitaHealth Rwanda',
    activeIngredient: 'Vitamins A, B-complex, C, D, E, Zinc, Iron',
    sideEffects: 'Mild nausea if taken on empty stomach',
    featured: true,
  },
  {
    name: 'Hydrocortisone Cream 1%',
    description: 'Topical corticosteroid cream for eczema, dermatitis, insect bites and skin irritation.',
    price: 2100,
    stock: 75,
    category: 'DERMATOLOGY',
    imageUrl: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400',
    prescriptionRequired: false,
    dosage: 'Apply thin layer to affected area 2-3 times daily.',
    manufacturer: 'DermaRwanda',
    activeIngredient: 'Hydrocortisone 1%',
    sideEffects: 'Skin thinning with prolonged use',
    featured: false,
  },
  {
    name: 'First Aid Kit Standard',
    description: 'Complete first aid kit with bandages, antiseptic, gloves, and emergency supplies.',
    price: 15000,
    stock: 25,
    category: 'FIRST_AID',
    imageUrl: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=400',
    prescriptionRequired: false,
    dosage: 'N/A - Emergency use',
    manufacturer: 'SafetyFirst Rwanda',
    activeIngredient: 'N/A',
    sideEffects: 'N/A',
    featured: true,
  },
  {
    name: 'Baby Paracetamol Syrup',
    description: 'Safe and effective fever and pain relief syrup for infants and young children.',
    price: 2200,
    stock: 60,
    category: 'BABY_CARE',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1663099606733-936edebc72d9?w=400',
    prescriptionRequired: false,
    dosage: 'Weight-based dosing: 15mg/kg every 6 hours.',
    manufacturer: 'BabyCare Rwanda',
    activeIngredient: 'Paracetamol 120mg/5ml',
    sideEffects: 'Very rare - consult doctor if rash appears',
    featured: false,
  },
  {
    name: 'Sertraline 50mg',
    description: 'SSRI antidepressant for depression, anxiety disorders and panic attacks.',
    price: 7800,
    stock: 30,
    category: 'MENTAL_HEALTH',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
    prescriptionRequired: true,
    dosage: '1 tablet daily, morning or evening.',
    manufacturer: 'MindCare Pharma',
    activeIngredient: 'Sertraline HCl 50mg',
    sideEffects: 'Nausea, insomnia, dizziness, dry mouth',
    featured: false,
  },
  {
    name: 'Oral Rehydration Salts',
    description: 'Electrolyte powder for rehydration after diarrhea, vomiting or excessive sweating.',
    price: 600,
    stock: 300,
    category: 'DIGESTIVE',
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=400',
    prescriptionRequired: false,
    dosage: 'Dissolve 1 sachet in 1 liter of clean water.',
    manufacturer: 'HydraPlus Rwanda',
    activeIngredient: 'Sodium chloride, Potassium chloride, Glucose',
    sideEffects: 'None when used as directed',
    featured: false,
  },
  {
    name: 'Hand Sanitizer 500ml',
    description: 'Alcohol-based hand sanitizer with 70% ethanol for effective germ elimination.',
    price: 1800,
    stock: 180,
    category: 'PERSONAL_CARE',
    imageUrl: 'https://images.unsplash.com/photo-1608564348103-2b78891150cf?w=400',
    prescriptionRequired: false,
    dosage: 'Apply to hands and rub for 20 seconds.',
    manufacturer: 'CleanRwanda',
    activeIngredient: 'Ethanol 70%, Glycerin',
    sideEffects: 'Skin dryness with frequent use',
    featured: false,
  },
  {
    name: 'Ciprofloxacin 500mg',
    description: 'Fluoroquinolone antibiotic for urinary tract, respiratory and skin infections.',
    price: 4800,
    stock: 50,
    category: 'ANTIBIOTICS',
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
    prescriptionRequired: true,
    dosage: '1 tablet twice daily for 7-14 days.',
    manufacturer: 'East Africa Meds',
    activeIngredient: 'Ciprofloxacin HCl 500mg',
    sideEffects: 'Nausea, diarrhea, photosensitivity',
    featured: false,
  },
];

async function main() {
  console.log('Seeding database...');

  const adminPassword = await bcrypt.hash('Sain1235', 10);
  const admin = await prisma.user.upsert({
    where: { email: 'massivsaine@pharmacare.rw' },
    update: { password: adminPassword, name: 'MASSIV Saine', role: 'ADMIN' },
    create: {
      name: 'MASSIV Saine',
      email: 'massivsaine@pharmacare.rw',
      password: adminPassword,
      role: 'ADMIN',
      phone: '+250788000001',
      address: 'KK 508 ST, Kigali, Rwanda',
    },
  });
  console.log('Admin created:', admin.email);

  const customerPassword = await bcrypt.hash('customer123', 10);
  const customer = await prisma.user.upsert({
    where: { email: 'customer@example.com' },
    update: {},
    create: {
      name: 'Jean Pierre Habimana',
      email: 'customer@example.com',
      password: customerPassword,
      role: 'CUSTOMER',
      phone: '+250788000002',
      address: 'KG 11 Ave, Kigali, Rwanda',
    },
  });
  console.log('Customer created:', customer.email);

  for (const product of products) {
    await prisma.product.upsert({
      where: { id: product.name.toLowerCase().replace(/\s+/g, '-') },
      update: product,
      create: { ...product, id: product.name.toLowerCase().replace(/\s+/g, '-') },
    });
  }

  console.log(`Seeded ${products.length} products`);
  console.log('Seeding complete!');
  console.log('\nTest credentials:');
  console.log('  Admin:    admin@pharmacare.rw / admin123');
  console.log('  Customer: customer@example.com / customer123');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
